// This file is auto-generated by the Caffeine build system.
// It provides the backend actor interface and factory for the frontend.
import { Actor, type ActorConfig, type HttpAgentOptions } from "@dfinity/agent";
import type { IDL } from "@dfinity/candid";
import type { _SERVICE } from "../../backend/backend.d";

export type backendInterface = _SERVICE;

export interface CreateActorOptions {
  agentOptions?: HttpAgentOptions;
  actorOptions?: Omit<ActorConfig, "canisterId">;
  agent?: import("@dfinity/agent").HttpAgent;
  processError?: (e: unknown) => never;
}

export type UploadFile = (file: ExternalBlob) => Promise<Uint8Array>;
export type DownloadFile = (bytes: Uint8Array) => Promise<ExternalBlob>;

export class ExternalBlob {
  private _bytes: Uint8Array | null = null;
  private _url: string | null = null;
  onProgress?: (progress: number) => void;

  static fromURL(url: string): ExternalBlob {
    const blob = new ExternalBlob();
    blob._url = url;
    return blob;
  }

  static fromBytes(bytes: Uint8Array): ExternalBlob {
    const blob = new ExternalBlob();
    blob._bytes = bytes;
    return blob;
  }

  async getBytes(): Promise<Uint8Array> {
    if (this._bytes) return this._bytes;
    if (this._url) {
      const resp = await fetch(this._url);
      const buf = await resp.arrayBuffer();
      this._bytes = new Uint8Array(buf);
      return this._bytes;
    }
    return new Uint8Array();
  }

  getURL(): string | null {
    return this._url;
  }
}

// Placeholder idlFactory - will be replaced by generated code
export const idlFactory: IDL.InterfaceFactory = ({ IDL: _IDL }) => {
  return _IDL.Service({});
};

export function createActor(
  canisterId: string,
  _uploadFile: UploadFile,
  _downloadFile: DownloadFile,
  options?: CreateActorOptions,
): backendInterface {
  const agent = options?.agent;
  if (!agent) {
    throw new Error("Agent required to create actor");
  }
  return Actor.createActor<backendInterface>(idlFactory, {
    agent,
    canisterId,
    ...options?.actorOptions,
  });
}
